<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-10-01 17:35

import uuid
=======
# Generated by Django 5.1.1 on 2024-09-24 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
>>>>>>> 295280dd14830525e1259534734d33c72263a24e
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurvivalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.survivalentry')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='entries',
            field=models.ManyToManyField(through='main.CartItem', to='main.survivalentry'),
        ),
    ]
