# Generated by Django 5.1.1 on 2024-09-17 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_survivalentry_delete_moodentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivalentry',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
